/* AutoGenerated Code, changes may be overwritten
* INPUT GRAMMAR:
* start := main=main $
* main := application | term
* term := abstraction | identifier=identifier | group
* abstraction := 'λ' parameter=identifier '\.' body=main
* application := func=main ' '? arg=term
* group := '\(' group=main '\)'
* identifier := '[a-zA-Z0-9_]+'
*/
type Nullable<T> = T | null;
type $$RuleType<T> = () => Nullable<T>;
export interface ASTNodeIntf {
    kind: ASTKinds;
}
export enum ASTKinds {
    start = "start",
    main_1 = "main_1",
    main_2 = "main_2",
    term_1 = "term_1",
    term_2 = "term_2",
    term_3 = "term_3",
    abstraction = "abstraction",
    application = "application",
    group = "group",
    identifier = "identifier",
    $EOF = "$EOF",
}
export interface start {
    kind: ASTKinds.start;
    main: main;
}
export type main = main_1 | main_2;
export type main_1 = application;
export type main_2 = term;
export type term = term_1 | term_2 | term_3;
export type term_1 = abstraction;
export interface term_2 {
    kind: ASTKinds.term_2;
    identifier: identifier;
}
export type term_3 = group;
export interface abstraction {
    kind: ASTKinds.abstraction;
    parameter: identifier;
    body: main;
}
export interface application {
    kind: ASTKinds.application;
    func: main;
    arg: term;
}
export interface group {
    kind: ASTKinds.group;
    group: main;
}
export type identifier = string;
export class Parser {
    private readonly input: string;
    private pos: PosInfo;
    private negating: boolean = false;
    private memoSafe: boolean = true;
    constructor(input: string) {
        this.pos = {overallPos: 0, line: 1, offset: 0};
        this.input = input;
    }
    public reset(pos: PosInfo) {
        this.pos = pos;
    }
    public finished(): boolean {
        return this.pos.overallPos === this.input.length;
    }
    public clearMemos(): void {
        this.$scope$main$memo.clear();
    }
    protected $scope$main$memo: Map<number, [Nullable<main>, PosInfo]> = new Map();
    public matchstart($$dpth: number, $$cr?: ErrorTracker): Nullable<start> {
        return this.run<start>($$dpth,
            () => {
                let $scope$main: Nullable<main>;
                let $$res: Nullable<start> = null;
                if (true
                    && ($scope$main = this.matchmain($$dpth + 1, $$cr)) !== null
                    && this.match$EOF($$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.start, main: $scope$main};
                }
                return $$res;
            });
    }
    public matchmain($$dpth: number, $$cr?: ErrorTracker): Nullable<main> {
        const fn = () => {
            return this.choice<main>([
                () => this.matchmain_1($$dpth + 1, $$cr),
                () => this.matchmain_2($$dpth + 1, $$cr),
            ]);
        };
        const $scope$pos = this.mark();
        const memo = this.$scope$main$memo.get($scope$pos.overallPos);
        if(memo !== undefined) {
            this.reset(memo[1]);
            return memo[0];
        }
        const $scope$oldMemoSafe = this.memoSafe;
        this.memoSafe = false;
        this.$scope$main$memo.set($scope$pos.overallPos, [null, $scope$pos]);
        let lastRes: Nullable<main> = null;
        let lastPos: PosInfo = $scope$pos;
        for(;;) {
            this.reset($scope$pos);
            const res = fn();
            const end = this.mark();
            if(end.overallPos <= lastPos.overallPos)
                break;
            lastRes = res;
            lastPos = end;
            this.$scope$main$memo.set($scope$pos.overallPos, [lastRes, lastPos]);
        }
        this.reset(lastPos);
        this.memoSafe = $scope$oldMemoSafe;
        return lastRes;
    }
    public matchmain_1($$dpth: number, $$cr?: ErrorTracker): Nullable<main_1> {
        return this.matchapplication($$dpth + 1, $$cr);
    }
    public matchmain_2($$dpth: number, $$cr?: ErrorTracker): Nullable<main_2> {
        return this.matchterm($$dpth + 1, $$cr);
    }
    public matchterm($$dpth: number, $$cr?: ErrorTracker): Nullable<term> {
        return this.choice<term>([
            () => this.matchterm_1($$dpth + 1, $$cr),
            () => this.matchterm_2($$dpth + 1, $$cr),
            () => this.matchterm_3($$dpth + 1, $$cr),
        ]);
    }
    public matchterm_1($$dpth: number, $$cr?: ErrorTracker): Nullable<term_1> {
        return this.matchabstraction($$dpth + 1, $$cr);
    }
    public matchterm_2($$dpth: number, $$cr?: ErrorTracker): Nullable<term_2> {
        return this.run<term_2>($$dpth,
            () => {
                let $scope$identifier: Nullable<identifier>;
                let $$res: Nullable<term_2> = null;
                if (true
                    && ($scope$identifier = this.matchidentifier($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.term_2, identifier: $scope$identifier};
                }
                return $$res;
            });
    }
    public matchterm_3($$dpth: number, $$cr?: ErrorTracker): Nullable<term_3> {
        return this.matchgroup($$dpth + 1, $$cr);
    }
    public matchabstraction($$dpth: number, $$cr?: ErrorTracker): Nullable<abstraction> {
        return this.run<abstraction>($$dpth,
            () => {
                let $scope$parameter: Nullable<identifier>;
                let $scope$body: Nullable<main>;
                let $$res: Nullable<abstraction> = null;
                if (true
                    && this.regexAccept(String.raw`(?:λ)`, $$dpth + 1, $$cr) !== null
                    && ($scope$parameter = this.matchidentifier($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:\.)`, $$dpth + 1, $$cr) !== null
                    && ($scope$body = this.matchmain($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.abstraction, parameter: $scope$parameter, body: $scope$body};
                }
                return $$res;
            });
    }
    public matchapplication($$dpth: number, $$cr?: ErrorTracker): Nullable<application> {
        return this.run<application>($$dpth,
            () => {
                let $scope$func: Nullable<main>;
                let $scope$arg: Nullable<term>;
                let $$res: Nullable<application> = null;
                if (true
                    && ($scope$func = this.matchmain($$dpth + 1, $$cr)) !== null
                    && ((this.regexAccept(String.raw`(?: )`, $$dpth + 1, $$cr)) || true)
                    && ($scope$arg = this.matchterm($$dpth + 1, $$cr)) !== null
                ) {
                    $$res = {kind: ASTKinds.application, func: $scope$func, arg: $scope$arg};
                }
                return $$res;
            });
    }
    public matchgroup($$dpth: number, $$cr?: ErrorTracker): Nullable<group> {
        return this.run<group>($$dpth,
            () => {
                let $scope$group: Nullable<main>;
                let $$res: Nullable<group> = null;
                if (true
                    && this.regexAccept(String.raw`(?:\()`, $$dpth + 1, $$cr) !== null
                    && ($scope$group = this.matchmain($$dpth + 1, $$cr)) !== null
                    && this.regexAccept(String.raw`(?:\))`, $$dpth + 1, $$cr) !== null
                ) {
                    $$res = {kind: ASTKinds.group, group: $scope$group};
                }
                return $$res;
            });
    }
    public matchidentifier($$dpth: number, $$cr?: ErrorTracker): Nullable<identifier> {
        return this.regexAccept(String.raw`(?:[a-zA-Z0-9_]+)`, $$dpth + 1, $$cr);
    }
    public test(): boolean {
        const mrk = this.mark();
        const res = this.matchstart(0);
        const ans = res !== null;
        this.reset(mrk);
        return ans;
    }
    public parse(): ParseResult {
        const mrk = this.mark();
        const res = this.matchstart(0);
        if (res)
            return {ast: res, errs: []};
        this.reset(mrk);
        const rec = new ErrorTracker();
        this.clearMemos();
        this.matchstart(0, rec);
        const err = rec.getErr()
        return {ast: res, errs: err !== null ? [err] : []}
    }
    public mark(): PosInfo {
        return this.pos;
    }
    private loop<T>(func: $$RuleType<T>, star: boolean = false): Nullable<T[]> {
        const mrk = this.mark();
        const res: T[] = [];
        for (;;) {
            const t = func();
            if (t === null) {
                break;
            }
            res.push(t);
        }
        if (star || res.length > 0) {
            return res;
        }
        this.reset(mrk);
        return null;
    }
    private run<T>($$dpth: number, fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn()
        if (res !== null)
            return res;
        this.reset(mrk);
        return null;
    }
    private choice<T>(fns: Array<$$RuleType<T>>): Nullable<T> {
        for (const f of fns) {
            const res = f();
            if (res !== null) {
                return res;
            }
        }
        return null;
    }
    private regexAccept(match: string, dpth: number, cr?: ErrorTracker): Nullable<string> {
        return this.run<string>(dpth,
            () => {
                const reg = new RegExp(match, "y");
                const mrk = this.mark();
                reg.lastIndex = mrk.overallPos;
                const res = this.tryConsume(reg);
                if(cr) {
                    cr.record(mrk, res, {
                        kind: "RegexMatch",
                        // We substring from 3 to len - 1 to strip off the
                        // non-capture group syntax added as a WebKit workaround
                        literal: match.substring(3, match.length - 1),
                        negated: this.negating,
                    });
                }
                return res;
            });
    }
    private tryConsume(reg: RegExp): Nullable<string> {
        const res = reg.exec(this.input);
        if (res) {
            let lineJmp = 0;
            let lind = -1;
            for (let i = 0; i < res[0].length; ++i) {
                if (res[0][i] === "\n") {
                    ++lineJmp;
                    lind = i;
                }
            }
            this.pos = {
                overallPos: reg.lastIndex,
                line: this.pos.line + lineJmp,
                offset: lind === -1 ? this.pos.offset + res[0].length : (res[0].length - lind - 1)
            };
            return res[0];
        }
        return null;
    }
    private noConsume<T>(fn: $$RuleType<T>): Nullable<T> {
        const mrk = this.mark();
        const res = fn();
        this.reset(mrk);
        return res;
    }
    private negate<T>(fn: $$RuleType<T>): Nullable<boolean> {
        const mrk = this.mark();
        const oneg = this.negating;
        this.negating = !oneg;
        const res = fn();
        this.negating = oneg;
        this.reset(mrk);
        return res === null ? true : null;
    }
    private memoise<K>(rule: $$RuleType<K>, memo: Map<number, [Nullable<K>, PosInfo]>): Nullable<K> {
        const $scope$pos = this.mark();
        const $scope$memoRes = memo.get($scope$pos.overallPos);
        if(this.memoSafe && $scope$memoRes !== undefined) {
        this.reset($scope$memoRes[1]);
        return $scope$memoRes[0];
        }
        const $scope$result = rule();
        if(this.memoSafe)
        memo.set($scope$pos.overallPos, [$scope$result, this.mark()]);
        return $scope$result;
    }
    private match$EOF(et?: ErrorTracker): Nullable<{kind: ASTKinds.$EOF}> {
        const res: {kind: ASTKinds.$EOF} | null = this.finished() ? { kind: ASTKinds.$EOF } : null;
        if(et)
            et.record(this.mark(), res, { kind: "EOF", negated: this.negating });
        return res;
    }
}
export function parse(s: string): ParseResult {
    const p = new Parser(s);
    return p.parse();
}
export interface ParseResult {
    ast: Nullable<start>;
    errs: SyntaxErr[];
}
export interface PosInfo {
    readonly overallPos: number;
    readonly line: number;
    readonly offset: number;
}
export interface RegexMatch {
    readonly kind: "RegexMatch";
    readonly negated: boolean;
    readonly literal: string;
}
export type EOFMatch = { kind: "EOF"; negated: boolean };
export type MatchAttempt = RegexMatch | EOFMatch;
export class SyntaxErr {
    public pos: PosInfo;
    public expmatches: MatchAttempt[];
    constructor(pos: PosInfo, expmatches: MatchAttempt[]) {
        this.pos = pos;
        this.expmatches = [...expmatches];
    }
    public toString(): string {
        return `Syntax Error at line ${this.pos.line}:${this.pos.offset}. Expected one of ${this.expmatches.map(x => x.kind === "EOF" ? " EOF" : ` ${x.negated ? 'not ': ''}'${x.literal}'`)}`;
    }
}
class ErrorTracker {
    private mxpos: PosInfo = {overallPos: -1, line: -1, offset: -1};
    private regexset: Set<string> = new Set();
    private pmatches: MatchAttempt[] = [];
    public record(pos: PosInfo, result: any, att: MatchAttempt) {
        if ((result === null) === att.negated)
            return;
        if (pos.overallPos > this.mxpos.overallPos) {
            this.mxpos = pos;
            this.pmatches = [];
            this.regexset.clear()
        }
        if (this.mxpos.overallPos === pos.overallPos) {
            if(att.kind === "RegexMatch") {
                if(!this.regexset.has(att.literal))
                    this.pmatches.push(att);
                this.regexset.add(att.literal);
            } else {
                this.pmatches.push(att);
            }
        }
    }
    public getErr(): SyntaxErr | null {
        if (this.mxpos.overallPos !== -1)
            return new SyntaxErr(this.mxpos, this.pmatches);
        return null;
    }
}